# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
inhibit_all_warnings!

target 'YUKitSample' do
    pod 'AFNetworking'#, '~> 3.1.0'
    pod 'BlocksKit'#, '~> 2.2.5'
    pod 'SDWebImage'#, '~> 3.7.5'
    pod 'MJRefresh'#, '~> 3.1.0'
    pod 'Masonry'#, '~> 1.0.0'
    pod 'YUDBModel'#, '~> 1.0.0'
    pod 'YUKit'#, '~> 2.0.3'
end

